[package]
name = "new-project"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.6"
axum-server = "0.7.1"
libphext = "0.1.7"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
